### ISSUE TITLE
Support for arbitrary SMTP headers

### ISSUE THREAD

**Issue by codegoalie** [gobuffalo/x#6]
I use SendGrid as my SMTP service and I'd like to use their [SMTP API](https://sendgrid.com/docs/API_Reference/SMTP_API/index.html) which allows you to specify some metadata about the email, such as specifying a category or schedule the time to send. This is done by setting the `X-SMTPAPI` header to a JSON string.

I think the most generic way to do this would be to add support for setting arbitrary headers. E.g. 

```go
m := mail.NewMessage()

m.SetHeader("X-SMTPAPI", smtpApiJsonString)
```

Do you think this would be something that fits within this package? I had considered implementing a separate `Message` and `Sender`. However, I think it would be 95% the same as this package.

If you think it's be a worthwhile addition, I'd be happy to take a crack at implementing it.

**Comment by markbates** [comment]
That sounds like a great idea! Would love to see a PR for it.
